### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by donatj** [avvmoto/buf-readerat#1]
Hey!

This is super useful and solves a huge performance issue I'm having with ReadAt! Thank you so much for your efforts on this!

I was wondering if you could throw a license file on this to clarify that it's OK to make use of?

I'd request MIT if possible ;)  Thanks!

**Comment by donatj** [comment]
I had this translated and sent it in an email - I don't know how good the translation was but 

> こんにちは。
> 
> 現在進行中のプロジェクト sqlread があります。 ここ数週間、MySQLのダンプに直接クエリーできるよう、開発に取り組んでいます。
> 
> それが実現すれば、ReadAtを大いに利用できるようになり、あなたのbuf-readeratライブラリはパフォーマンスが劇的に向上されます。しかし、現時点ではライセンスがないためそれを使用することができず、おそらく完全な著作権保護が推測されます。
> 
> 彼らが私にとって最も柔軟性を提供するので、あなたがMIT（あなたが過去に使ったことを見ているように）かBSD LICENSEのどちらかを選ぶなら、私は非常に感謝します。

**Comment by avvmoto** [comment]
@donatj 
Hello, thank you for using this package. I've set MIT license to this package at #2 .  Please keep enjoy using this.
